""" minor tweaks

Revision ID: 2598963c556f
Revises: f17f3dc25abd
Create Date: 2025-04-07 17:29:35.526021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2598963c556f'
down_revision: Union[str, None] = 'f17f3dc25abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('telephone', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'invoice_item', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_item', type_='unique')
    op.drop_column('invoice', 'telephone')
    # ### end Alembic commands ###
