""" minor tweaks

Revision ID: 49090e0611eb
Revises: 2598963c556f
Create Date: 2025-04-07 17:36:12.364672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49090e0611eb'
down_revision: Union[str, None] = '2598963c556f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('uid_number', sa.String(length=50), nullable=True))
    op.add_column('invoice', sa.Column('markt_id', sa.String(length=50), nullable=True))
    op.add_column('invoice', sa.Column('document_nr', sa.String(length=100), nullable=True))
    op.add_column('invoice', sa.Column('time', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'time')
    op.drop_column('invoice', 'document_nr')
    op.drop_column('invoice', 'markt_id')
    op.drop_column('invoice', 'uid_number')
    # ### end Alembic commands ###
