"""update user model

Revision ID: 86f78c9436ea
Revises: f25d73d7b29d
Create Date: 2025-03-27 21:34:38.762769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f78c9436ea'
down_revision: Union[str, None] = 'f25d73d7b29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_constraint('user_user_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_user_id_key', 'user', ['user_id'])
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
