"""add invoice item model

Revision ID: f17f3dc25abd
Revises: 7f399e60d961
Create Date: 2025-04-07 17:20:53.813445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f17f3dc25abd'
down_revision: Union[str, None] = '7f399e60d961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'invoice', ['id'])
    op.drop_column('invoice', 'uid_number')
    op.drop_column('invoice', 'document_nr')
    op.drop_column('invoice', 'markt_id')
    op.drop_column('invoice', 'processing_errors')
    op.drop_column('invoice', 'items')
    op.drop_column('invoice', 'time')
    op.drop_column('invoice', 'telephone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('time', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('processing_errors', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('markt_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('document_nr', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('uid_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice', type_='unique')
    op.drop_table('invoice_item')
    # ### end Alembic commands ###
