"""user uuid for user id

Revision ID: f25d73d7b29d
Revises: 04dbcb712ad2
Create Date: 2025-03-27 11:46:49.486471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25d73d7b29d'
down_revision: Union[str, None] = '04dbcb712ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index('ix_user_id', table_name='user')
    op.create_unique_constraint(None, 'user', ['user_id'])
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
